### ISSUE TITLE
Add validators

### ISSUE THREAD

**Issue by bkielbasa** [bkielbasa/wio-forms#54]
In PR #52 I added some walidators. I will need a list of validators witch will be available out of the box. My suggestion is:

 * pesel
 * phone_number (but with some parameters)

any other ideas @michaloo?

**Comment by michaloo** [comment]
I will think about this. We have some new this year - Szlachetna Paczka will be run also outside Poland in Chicago USA - our address data validators should be prepared for that :)

**Comment by bkielbasa** [comment]
Congrats!

I will add regex validator which should add good flexibility -> http://symfony.com/doc/current/reference/constraints/Regex.html

I thought about them because phone number/pesel etc will be used very often so I think it is good idea to prepare a component for that.

**Comment by michaloo** [comment]
👍
